BAG OF WORDS

In [1]:
import numpy as np
import pandas as pd

In [2]:
import pandas as pd

df = pd.DataFrame({
    "text": [
        "students love data science",
        "teachers teach data science",
        "students hate homework",
        "homework is important"
    ],
    "output": [1, 1, 0, 0]
})

df


text  output
0   students love data science       1
1  teachers teach data science       1
2       students hate homework       0
3        homework is important       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
bow = cv.fit_transform(df['text'])

In [6]:
#vocabulary
print(cv.vocabulary_)

{'students': 7, 'love': 5, 'data': 0, 'science': 6, 'teachers': 9, 'teach': 8, 'hate': 1, 'homework': 2, 'is': 4, 'important': 3}


In [7]:
bow.toarray()

array([[1, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0]])

N-GRAMS

In [10]:
import pandas as pd

df = pd.DataFrame({
    "text": [
        "students love data science",
        "teachers teach data science",
        "students hate homework",
        "homework is important"
    ],
    "output": [1, 1, 0, 0]
})

df

text  output
0   students love data science       1
1  teachers teach data science       1
2       students hate homework       0
3        homework is important       0

In [14]:
import pandas as pd
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [15]:
def get_bigrams(text):
    tokens = word_tokenize(text.lower())
    bigrams = list(zip(tokens, tokens[1:]))
    return bigrams


In [16]:
df['bigrams'] = df['text'].apply(get_bigrams)
print(df[['text', 'bigrams']])


                          text  \
0   students love data science   
1  teachers teach data science   
2       students hate homework   
3        homework is important   

                                             bigrams  
0  [(students, love), (love, data), (data, science)]  
1  [(teachers, teach), (teach, data), (data, scie...  
2               [(students, hate), (hate, homework)]  
3                  [(homework, is), (is, important)]  


BI GRAMS

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd


In [18]:
cv = CountVectorizer(ngram_range=(2,2))

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'students love': 6, 'love data': 4, 'data science': 0, 'teachers teach': 8, 'teach data': 7, 'students hate': 5, 'hate homework': 1, 'homework is': 2, 'is important': 3}


In [21]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 0 1 0 1 0 0]]
[[1 0 0 0 0 0 0 1 1]]
[[0 1 0 0 0 1 0 0 0]]


TI GRAMS


In [22]:

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [23]:
bow = cv.fit_transform(df['text'])

In [24]:
print(cv.vocabulary_)

{'students love data': 3, 'love data science': 1, 'teachers teach data': 5, 'teach data science': 4, 'students hate homework': 2, 'homework is important': 0}


In [25]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0 1 0 0]]
[[0 0 0 0 1 1]]
[[0 0 1 0 0 0]]


TF-IDF (Term frequency- Inverse document frequency)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
docs = [
    "data science is cool",
    "machine learning is part of data science",
    "data is powerful"
]

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [36]:
arr = tfid.fit_transform(df['text']).toarray()

In [37]:
arr

array([[0.46580855, 0.        , 0.        , 0.        , 0.        ,
        0.59081908, 0.46580855, 0.46580855, 0.        , 0.        ],
       [0.43779123, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.43779123, 0.        , 0.55528266, 0.55528266],
       [0.        , 0.66767854, 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.52640543, 0.        , 0.        ],
       [0.        , 0.        , 0.48693426, 0.61761437, 0.61761437,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

In [38]:
print(tfid.idf_)

[1.51082562 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073
 1.51082562 1.51082562 1.91629073 1.91629073]
